"""add_stateless_match_clocks

Revision ID: 70816d0e2650
Revises: c065ce81b12c
Create Date: 2026-06-07 10:53:42.504101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70816d0e2650'
down_revision: Union[str, Sequence[str], None] = 'c065ce81b12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('white_time_left', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('black_time_left', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('last_move_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'last_move_at')
    op.drop_column('matches', 'black_time_left')
    op.drop_column('matches', 'white_time_left')
    # ### end Alembic commands ###
