"""add match rating outcomes

Revision ID: c065ce81b12c
Revises: b752a389d8f9
Create Date: 2026-06-07 10:25:38.750852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c065ce81b12c'
down_revision: Union[str, Sequence[str], None] = 'b752a389d8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_id', sa.UUID(), nullable=True))
    op.add_column('matches', sa.Column('white_rating_change', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('black_rating_change', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'users', ['winner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'black_rating_change')
    op.drop_column('matches', 'white_rating_change')
    op.drop_column('matches', 'winner_id')
    # ### end Alembic commands ###
